# Generated by Django 4.0.4 on 2022-06-01 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_att_alter_attendance_info_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_info',
            name='in_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 14, 29, 48, 835577)),
        ),
    ]
